### ISSUE TITLE
Recommendations for reducing attack vectors

### ISSUE THREAD

**Issue by bauschri** [efchatz/pandora#1]
Hey!

Great work, thanks for sharing!

Do you mind sharing your thoughts about more secure password management solutions? 

Using KeePass database with challenge-response mode of TOTP devices (yubikeys) would protect against bulk exports on a compromised client?

cheerio

**Comment by efchatz** [comment]
Hi, thank you!

A detailed analysis will be included in our research paper. It will probably be published in the next 2 months.

In the meantime, you can use a password manager that it is not covered in this tool.

**Comment by efchatz** [comment]
Here is a link to our work: https://arxiv.org/abs/2404.00423
