### ISSUE TITLE
Duplicate Header File findPlugin.h/FindPlugin.h in \headers\core\

### ISSUE THREAD

**Issue by L1-0** [efchatz/pandora#7]
Hi, I'm getting an issue on extracting/compiling from source on a Windows machine, where file names are not case-sensitive.

\pandora-1.0.2\headers\core\FindPlugin.h
\pandora-1.0.2\headers\core\findPlugin.h

![pandora-1 0 2_headers_core_hfile](https://github.com/efchatz/pandora/assets/123986259/c6bdce5f-79b1-4e41-89cd-beb2b0684455)

If it is possible you should stick to one of them.

Greetings

**Comment by L1-0** [comment]
I guess as a workaround just extract \pandora-1.0.2\headers\core\findPlugin.h manually and work with that as it is the newer one.

**Comment by efchatz** [comment]
Hi, thank you for the observation. The FindPlugin.h was duplicated. It was removed.
